# Generated by Django 4.1.7 on 2023-04-11 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_question_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 11, 9, 26, 11, 553277, tzinfo=datetime.timezone.utc)),
        ),
    ]
