# Generated by Django 4.1.7 on 2023-04-11 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0014_alter_question_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 11, 10, 8, 1, 464391, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
