# Generated by Django 4.1.7 on 2023-04-13 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0017_alter_question_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 4, 13, 10, 37, 51, 62203, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
