# Generated by Django 4.1.7 on 2023-04-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='last_name',
        ),
    ]
