# Generated by Django 4.1.7 on 2023-04-11 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_remove_recruiter_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='company_email',
            field=models.EmailField(default='', max_length=255, verbose_name='company email address'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company_name',
            field=models.CharField(default='', max_length=255, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='recruiter', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
