# Generated by Django 4.1.7 on 2023-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authy", "0008_profile_company_email_profile_company_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Choose",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("c_id", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
